apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  creationTimestamp: null
  name: helloservice
spec:
  gateways:
  - public-gateway.istio-system
  - mesh
  hosts:
  - helloservice.pod-tato-head-dev.35.194.25.156.nip.io
  - helloservice
  http:
  - route:
    - destination:
        host: helloservice.pod-tato-head-dev.svc.cluster.local
